### ISSUE TITLE
رپو به حدی رسیده که بهتره پوشه بندی کنیم فایل هارو

### ISSUE THREAD

**Issue by Jiwe-Mobarez** [ososIran/os-plan-coalition#5]
بنظرم بهتره برای نظم بهتره یه پوشه src درست بشه و تمام فایل های odt و tex داخل اون ها برن. بیننده ها هم فقط محصول های نهایی رو میخونن و میبینن و با فایل های پروداکشن گیج نمیشن که این عددا و فایلا چیه.

**Comment by osAIran** [comment]
Nice suggestion. Thank you!
